import Link from "next/link";
import { getAllPosts } from "../utils/features";

export const metadata = {
  title: "All posts - tut7",
  description: "Generated by asif",
};
export async function generateStaticParams() {
  return [{ id: "1" }, { id: "2" }, { id: "3" }, { id: "4" }, { id: "5" }];
}
const page = async () => {
  const posts = await getAllPosts();
  return (
    <>
      {posts?.map((post) => (
        <div key={post.id} className="flex col gp-4">
          <h1>{post.title}</h1>
          <p>{post.body}</p>
          <Link href={`/post/${post.id}`}>visit Post</Link>
        </div>
      ))}
    </>
  );
};

export default page;
