export default function Head() {
    return (
      <>
        <title>About - Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by MyNextTutor" />
        <link rel="icon" href="/favicon.ico" />
      </>
    )
  }
  