import './globals.css'

export const metadata = {
  title: 'tut7',
  description: 'Generated by asif',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
